#!/usr/bin/env bash

# Put your paths here!

# Path to the database as generated by the matlab scripts
database_path=

# If you need transcriptions, put the path to the WSJ root folder here
wsj0_root=

python -m padertorch.contrib.data.wsj0_mix.create_json \
	--database_path ${database_path} \
	--wsj0_root ${wsj0_root} \
	--json_path wsj0_mix_8k.json \
	--num_speakers 2 --num_speakers 3 \
	--signal_length min \
	--sample_rate wav8k