#!/usr/bin/env bash

# Put your paths here!
if [[ "$(hostname -d)" == nt.uni-paderborn.de ]]; then
	# NT specific defaults
	database_path=/net/db/merl_speaker_mixtures/data
	wsj0_root=/net/db/wsj
elif [[ "${PC2SYSNAME}" == OCULUS ]]; then
	database_path=/scratch/hpc-prf-nt1/cbj/net/db/merl_speaker_mixtures
	wsj0_root=/scratch/hpc-prf-nt1/cbj/net/db/wsj
else
	# Path to the database as generated by the matlab scripts
	database_path=

	# If you need transcriptions, put the path to the WSJ root folder here
	wsj0_root=
fi

python -m padertorch.contrib.data.wsj0_mix.create_json \
	--database_path ${database_path} \
	--wsj0_root ${wsj0_root} \
	--json_path wsj0_mix_min_8k.json \
	--num_speakers 2 --num_speakers 3 \
	--signal_length min \
	--sample_rate wav8k